### ISSUE TITLE
--xlimits does not work when there are no changepoints

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_stats#46]
If there are no changepoints within the `xlimits` provided by the user, the plotting script produces a traceback:

```python-traceback
Traceback (most recent call last):
  File "../bin/plot_krun_results", line 1643, in <module>
    inset_xlimits=options.inset_xlimits)
  File "../bin/plot_krun_results", line 361, in main
    core_cycles, cycles_ylimits, inset_xlimits)
  File "../bin/plot_krun_results", line 986, in draw_page
    p_exec_charts[index].plot_stack()
  File "../bin/plot_krun_results", line 523, in plot_stack
    self.plot_wallclock_times()
  File "../bin/plot_krun_results", line 587, in plot_wallclock_times
    self._plot_steady_equivalent(self.wallclock_axis)
  File "../bin/plot_krun_results", line 672, in _plot_steady_equivalent
    if (self.segment_means[0] + self.segment_vars[0] >= lower_bound and
AttributeError: 'ProcessExecChart' object has no attribute 'segment_vars'
```

Due to the same bug, when the user has passed in `--xlimits` and there are no changpoints within the bounds, insets do not correctly plot steady segment equivalent data.

**Comment by snim2** [comment]
This happens when the JSON file contains changepoint data, but there are no changepoints within the specified xlimits.

**Comment by snim2** [comment]
There is a branch (fix-issue-46) for fixing this issue, but it needs some more careful testing before we raise  PR.
