### ISSUE TITLE
Missing pexecs cause a crash in R code

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_stats#61]
This traceback is from a file where an individual pexec crashed:

```python-traceback
$ ../bin/warmup_stats --output-plots breaks.pdf breaks-warmup-stats.json.bz2 
.../warmup_stats/bin/mark_changepoints_in_json:224: RuntimeWarning: divide by zero encountered in log
  pen_value=15.0*numpy.log(len(p_exec)))
.../warmup_stats/work/pylibs/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in multiple.meanvar.norm(data, mul.method = method, penalty, pen.value,  : 
  Minimum segment legnth is too large to include a change in this data

  warnings.warn(x, RRuntimeWarning)
.../warmup_stats/work/pylibs/rpy2/rinterface/__init__.py:186: RRuntimeWarning: In addition: 
  warnings.warn(x, RRuntimeWarning)
.../warmup_stats/work/pylibs/rpy2/rinterface/__init__.py:186: RRuntimeWarning: There were 26 warnings (use warnings() to see them)
  warnings.warn(x, RRuntimeWarning)
.../warmup_stats/work/pylibs/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File ".../warmup_stats/bin/mark_changepoints_in_json", line 295, in <module>
    main(options.json_files[0], options.delta, options.steady_state)
  File ".../warmup_stats/bin/mark_changepoints_in_json", line 197, in main
    segments = get_segments(cpt, delta, steady_state, p_exec, outliers)
  File ".../warmup_stats/bin/mark_changepoints_in_json", line 224, in get_segments
    pen_value=15.0*numpy.log(len(p_exec)))
  File ".../warmup_stats/work/pylibs/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File ".../warmup_stats/work/pylibs/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in multiple.meanvar.norm(data, mul.method = method, penalty, pen.value,  : 
  Minimum segment legnth is too large to include a change in this data

Traceback (most recent call last):
  File "../bin/warmup_stats", line 488, in <module>
    main(options)
  File "../bin/warmup_stats", line 404, in main
    benchmark.mark_changepoints()
  File "../bin/warmup_stats", line 349, in mark_changepoints
    output = subprocess.check_output(' '.join(cli), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '/usr/bin/python2.7 .../warmup_stats/bin/mark_changepoints_in_json -s 375 breaks-warmup-stats_outliers_w150.json.bz2' returned non-zero exit status 1
```

**Comment by snim2** [comment]
This is a problem for the tabling scripts, also.
